### ISSUE TITLE
To make 'model.py' compatible with Torch 2.1

### ISSUE THREAD

**Issue by lijinbio** [bowang-lab/scGPT#69] opened 2023-08-24 10:33 UTC
Hello,

Thanks for the package. Due to the CUDA version on my server being 12.1, I need to install a newer version of Torch, specifically version 2.1. However, I encountered the following error regarding the 'model.py' when I attempted to run Step 4 of the notebook located at https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Annotation.ipynb. Kindly find the error message provided below. Could you please help suggest a resolution for this error? Thank you.

```
random masking at epoch   1, ratio of masked values in train:  0.0000
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[32], line 25
     16 valid_loader = prepare_dataloader(
     17     valid_data_pt,
     18     batch_size=eval_batch_size,
   (...)
     21     drop_last=False,
     22 )
     24 if config.do_train:
---> 25     train(
     26         model,
     27         loader=train_loader,
     28     )
     29 val_loss, val_err = evaluate(
     30     model,
     31     loader=valid_loader,
     32 )
     33 elapsed = time.time() - epoch_start_time

Cell In[31], line 32, in train(model, loader)
     30 src_key_padding_mask = input_gene_ids.eq(vocab[pad_token])
     31 with torch.cuda.amp.autocast(enabled=config.amp):
---> 32     output_dict = model(
     33         input_gene_ids,
     34         input_values,
     35         src_key_padding_mask=src_key_padding_mask,
     36         batch_labels=batch_labels if INPUT_BATCH_LABELS or config.DSBN else None,
     37         CLS=CLS,
     38         CCE=CCE,
     39         MVC=MVC,
     40         ECS=ECS,
     41         do_sample=do_sample_in_train,
     42         #generative_training=False
     43     )
     45     masked_positions = input_values.eq(mask_value)  # the postions to predict
     46     loss = 0.0

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /usr/local/lib/python3.10/site-packages/scgpt/model/model.py:333, in TransformerModel.forward(self, src, values, src_key_padding_mask, batch_labels, CLS, CCE, MVC, ECS, do_sample)
    302 def forward(
    303     self,
    304     src: Tensor,
   (...)
    312     do_sample: bool = False,
    313 ) -> Mapping[str, Tensor]:
    314     """
    315     Args:
    316         src (:obj:`Tensor`): token ids, shape [batch_size, seq_len]
   (...)
    331         dict of output Tensors.
    332     """
--> 333     transformer_output = self._encode(
    334         src, values, src_key_padding_mask, batch_labels
    335     )
    336     if self.use_batch_labels:
    337         batch_emb = self.batch_encoder(batch_labels)  # (batch, embsize)

File /usr/local/lib/python3.10/site-packages/scgpt/model/model.py:182, in TransformerModel._encode(self, src, values, src_key_padding_mask, batch_labels)
    179 else:
    180     total_embs = self.bn(total_embs.permute(0, 2, 1)).permute(0, 2, 1)
--> 182 output = self.transformer_encoder(
    183     total_embs, src_key_padding_mask=src_key_padding_mask
    184 )
    185 return output

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/transformer.py:332, in TransformerEncoder.forward(self, src, mask, src_key_padding_mask, is_causal)
    330 why_not_sparsity_fast_path = ''
    331 str_first_layer = "self.layers[0]"
--> 332 batch_first = first_layer.self_attn.batch_first
    333 if not hasattr(self, "use_nested_tensor"):
    334     why_not_sparsity_fast_path = "use_nested_tensor attribute not present"

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1695, in Module.__getattr__(self, name)
   1693     if name in modules:
   1694         return modules[name]
-> 1695 raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

AttributeError: 'FlashMHA' object has no attribute 'batch_first'
```

**Comment by lijinbio** [comment] 2023-08-24 14:56
Hello @subercui, if the error message above is not quickly fixable for now, do you mind suggesting if there is a way to install flash-attn and scGPT for CUDA 12.1? I have tried to follow the installation steps in README.mkd, but without success. The installation has been quite challenging. Additionally, I noticed that many dependent packages are in their previous versions at https://github.com/bowang-lab/scGPT/blob/main/pyproject.toml and https://github.com/bowang-lab/scGPT/blob/main/poetry.lock. Would you kindly suggest any solutions to easily install scGPT? Thank you very much.

**Comment by subercui** [comment] 2023-08-24 15:16
Have you got the flash-attn installed properly? There are test files in their official repo and you can run for a test. https://github.com/Dao-AILab/flash-attention/blob/main/benchmarks/benchmark_flash_attention.py

**Comment by lijinbio** [comment] 2023-08-24 17:06
> 

Hello @subercui, thank you so much for your prompt reply. Yes, I tried your suggested workaround solution, and I believe it has resolved the previous error. However, a new error is now appearing, and I suspect it is once again caused by the PyTorch version I am using. Please find the error message at the end. By the way, I am using flash-attn v1.0.4, and the benchmark code you shared with me cannot run directly due to changes in the interfaces of the flash-attn package. Thank you.

Regarding the dependencies listed at https://github.com/bowang-lab/scGPT/blob/main/pyproject.toml, if I understand correctly, we need to install torch v1.13.0 precisely. Given that I have CUDA 12.1, I'm unsure about the process of installing torch v1.13.0 built to work with CUDA 12.1. Do you have any suggestions for installing v1.13.0 to be compatible with CUDA 12.1? Thank you so much for your help.

```
random masking at epoch   1, ratio of masked values in train:  0.0000
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[34], line 25
     16 valid_loader = prepare_dataloader(
     17     valid_data_pt,
     18     batch_size=eval_batch_size,
   (...)
     21     drop_last=False,
     22 )
     24 if config.do_train:
---> 25     train(
     26         model,
     27         loader=train_loader,
     28     )
     29 val_loss, val_err = evaluate(
     30     model,
     31     loader=valid_loader,
     32 )
     33 elapsed = time.time() - epoch_start_time

Cell In[33], line 32, in train(model, loader)
     30 src_key_padding_mask = input_gene_ids.eq(vocab[pad_token])
     31 with torch.cuda.amp.autocast(enabled=config.amp):
---> 32     output_dict = model(
     33         input_gene_ids,
     34         input_values,
     35         src_key_padding_mask=src_key_padding_mask,
     36         batch_labels=batch_labels if INPUT_BATCH_LABELS or config.DSBN else None,
     37         CLS=CLS,
     38         CCE=CCE,
     39         MVC=MVC,
     40         ECS=ECS,
     41         do_sample=do_sample_in_train,
     42         #generative_training=False
     43     )
     45     masked_positions = input_values.eq(mask_value)  # the postions to predict
     46     loss = 0.0

File /usr/local_dev/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local_dev/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /usr/local_dev/lib/python3.10/site-packages/scgpt/model/model.py:333, in TransformerModel.forward(self, src, values, src_key_padding_mask, batch_labels, CLS, CCE, MVC, ECS, do_sample)
    302 def forward(
    303     self,
    304     src: Tensor,
   (...)
    312     do_sample: bool = False,
    313 ) -> Mapping[str, Tensor]:
    314     """
    315     Args:
    316         src (:obj:`Tensor`): token ids, shape [batch_size, seq_len]
   (...)
    331         dict of output Tensors.
    332     """
--> 333     transformer_output = self._encode(
    334         src, values, src_key_padding_mask, batch_labels
    335     )
    336     if self.use_batch_labels:
    337         batch_emb = self.batch_encoder(batch_labels)  # (batch, embsize)

File /usr/local_dev/lib/python3.10/site-packages/scgpt/model/model.py:182, in TransformerModel._encode(self, src, values, src_key_padding_mask, batch_labels)
    179 else:
    180     total_embs = self.bn(total_embs.permute(0, 2, 1)).permute(0, 2, 1)
--> 182 output = self.transformer_encoder(
    183     total_embs, src_key_padding_mask=src_key_padding_mask
    184 )
    185 return output

File /usr/local_dev/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local_dev/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /usr/local_dev/lib/python3.10/site-packages/torch/nn/modules/transformer.py:387, in TransformerEncoder.forward(self, src, mask, src_key_padding_mask, is_causal)
    384 is_causal = _detect_is_causal_mask(mask, is_causal, seq_len)
    386 for mod in self.layers:
--> 387     output = mod(output, src_mask=mask, is_causal=is_causal, src_key_padding_mask=src_key_padding_mask_for_layers)
    389 if convert_to_nested:
    390     output = output.to_padded_tensor(0., src.size())

File /usr/local_dev/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local_dev/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /usr/local_dev/lib/python3.10/site-packages/scgpt/model/model.py:701, in FlashTransformerEncoderLayer.forward(self, src, src_mask, src_key_padding_mask, **kwargs)
    699     src = src + self.dropout2(src2)
    700 else:
--> 701     src2 = self.self_attn(src, key_padding_mask=src_key_padding_mask_)[0]
    702     src = src + self.dropout1(src2)
    703     src = self.norm1(src)

File /usr/local_dev/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local_dev/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /usr/local_dev/lib/python3.10/site-packages/flash_attn/flash_attention.py:99, in FlashMHA.forward(self, x, key_padding_mask, need_weights)
     97 qkv = self.Wqkv(x)
     98 qkv = rearrange(qkv, 'b s (three h d) -> b s three h d', three=3, h=self.num_heads)
---> 99 context, attn_weights = self.inner_attn(qkv, key_padding_mask=key_padding_mask,
    100                                         need_weights=need_weights, causal=self.causal)
    101 return self.out_proj(rearrange(context, 'b s h d -> b s (h d)')), attn_weights

File /usr/local_dev/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local_dev/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /usr/local_dev/lib/python3.10/site-packages/flash_attn/flash_attention.py:57, in FlashAttention.forward(self, qkv, key_padding_mask, causal, cu_seqlens, max_s, need_weights)
     55         x_unpad, indices, cu_seqlens, max_s = unpad_input(x, key_padding_mask)
     56         x_unpad = rearrange(x_unpad, 'nnz (three h d) -> nnz three h d', three=3, h=nheads)
---> 57         output_unpad = flash_attn_unpadded_qkvpacked_func(
     58             x_unpad, cu_seqlens, max_s, self.dropout_p if self.training else 0.0,
     59             softmax_scale=self.softmax_scale, causal=causal
     60         )
     61         output = rearrange(pad_input(rearrange(output_unpad, 'nnz h d -> nnz (h d)'),
     62                                     indices, batch_size, seqlen),
     63                         'b s (h d) -> b s h d', h=nheads)
     64 else:

File /usr/local_dev/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py:256, in flash_attn_unpadded_qkvpacked_func(qkv, cu_seqlens, max_seqlen, dropout_p, softmax_scale, causal, return_attn_probs, deterministic)
    231 def flash_attn_unpadded_qkvpacked_func(qkv, cu_seqlens, max_seqlen, dropout_p, softmax_scale=None,
    232                                        causal=False, return_attn_probs=False, deterministic=False):
    233     """dropout_p should be set to 0.0 during evaluation
    234     Arguments:
    235         qkv: (total, 3, nheads, headdim), where total = total number of tokens in the batch.
   (...)
    254             pattern (negative means that location was dropped, nonnegative means it was kept).
    255     """
--> 256     return FlashAttnQKVPackedFunc.apply(qkv, cu_seqlens, max_seqlen, dropout_p, softmax_scale,
    257                                         causal, return_attn_probs, deterministic)

File /usr/local_dev/lib/python3.10/site-packages/torch/autograd/function.py:539, in Function.apply(cls, *args, **kwargs)
    536 if not torch._C._are_functorch_transforms_active():
    537     # See NOTE: [functorch vjp and autograd interaction]
    538     args = _functorch.utils.unwrap_dead_wrappers(args)
--> 539     return super().apply(*args, **kwargs)  # type: ignore[misc]
    541 if cls.setup_context == _SingleLevelFunction.setup_context:
    542     raise RuntimeError(
    543         "In order to use an autograd.Function with functorch transforms "
    544         "(vmap, grad, jvp, jacrev, ...), it must override the setup_context "
    545         "staticmethod. For more details, please see "
    546         "https://pytorch.org/docs/master/notes/extending.func.html"
    547     )

File /usr/local_dev/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py:58, in FlashAttnQKVPackedFunc.forward(ctx, qkv, cu_seqlens, max_seqlen, dropout_p, softmax_scale, causal, return_softmax, deterministic)
     56 if softmax_scale is None:
     57     softmax_scale = qkv.shape[-1] ** (-0.5)
---> 58 out, softmax_lse, rng_state, S_dmask = _flash_attn_forward(
     59     qkv[:, 0], qkv[:, 1], qkv[:, 2], torch.empty_like(qkv[:, 0]), cu_seqlens, cu_seqlens,
     60     max_seqlen, max_seqlen, dropout_p, softmax_scale, causal=causal,
     61     return_softmax=return_softmax
     62 )
     63 ctx.save_for_backward(qkv, out, softmax_lse, cu_seqlens, rng_state)
     64 ctx.dropout_p = dropout_p

File /usr/local_dev/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py:21, in _flash_attn_forward(q, k, v, out, cu_seqlens_q, cu_seqlens_k, max_seqlen_q, max_seqlen_k, dropout_p, softmax_scale, causal, return_softmax, num_splits, generator)
     13 def _flash_attn_forward(q, k, v, out, cu_seqlens_q, cu_seqlens_k, max_seqlen_q, max_seqlen_k,
     14                         dropout_p, softmax_scale, causal, return_softmax, num_splits=0,
     15                         generator=None):
     16     """
     17     num_splits: how much to parallelize over the seqlen_q dimension. num_splits=0 means
     18     it will be set by an internal heuristic. We're exposing num_splits mostly for benchmarking.
     19     Don't change it unless you know what you're doing.
     20     """
---> 21     softmax_lse, rng_state, *rest = flash_attn_cuda.fwd(
     22         q, k, v, out, cu_seqlens_q, cu_seqlens_k, max_seqlen_q, max_seqlen_k, dropout_p,
     23         softmax_scale, False, causal, return_softmax, num_splits, generator
     24     )
     25     # if out.isnan().any() or softmax_lse.isnan().any():
     26     #     breakpoint()
     27     S_dmask = rest[0] if return_softmax else None

RuntimeError: Expected is_sm90 || is_sm8x || is_sm75 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

**Comment by subercui** [comment] 2023-08-24 22:16
Hi, this is related to flash-attn, it needs a newer version of GPU, I think specifically, the Turing generation and afterward. 

If you have a newer GPU, you can first verify your flash-attn on it by https://github.com/bowang-lab/scGPT/issues/69#issuecomment-1691877954 . Then I think your current installation may work as well.

Please also see the discussion here at #39. We are currently in the process trying to support running with native pytorch.

**Comment by lijinbio** [comment] 2023-08-25 00:18
> Have you got the flash-attn installed properly? There are test files in their official repo and you can run for a test. https://github.com/Dao-AILab/flash-attention/blob/main/benchmarks/benchmark_flash_attention.py

Hello @subercui, I tried to run the code; however, it cannot run due to the error below. It appears that flash_attn v1.0.4 has different interfaces that are incompatible with the benchmark codes. What do you think? Thanks.

```
$ python benchmark_flash_attention.py 
Traceback (most recent call last):
  File "benchmark_flash_attention.py", line 12, in <module>
    from flash_attn.utils.benchmark import benchmark_fwd_bwd, benchmark_combined
ImportError: cannot import name 'benchmark_fwd_bwd' from 'flash_attn.utils.benchmark' (/usr/local/lib/python3.10/site-packages/flash_attn-1.0.4-py3.10-linux-x86_64.egg/flash_attn/utils/benchmark.py)
```

**Comment by lijinbio** [comment] 2023-08-25 00:25
> Hi, this is related to flash-attn, it needs a newer version of GPU, I think specifically, the Turing generation and afterward.
> 
> If you have a newer GPU, you can first verify your flash-attn on it by [#69 (comment)](https://github.com/bowang-lab/scGPT/issues/69#issuecomment-1691877954) . Then I think your current installation may work as well.
> 
> Please also see the discussion here at #39. We are currently in the process trying to support running with native pytorch MHA as well to support a generic GPU and CPU running mode

Hello @subercui, I'm not entirely sure if my GPU is supported by flash-attn or not. Below is my GPU device information. Could you please confirm if my GPU device is too old to be compatible with flash-attn? If flash-attn is not an option, would you kindly suggest an alternative method to run scGPT on my old GPU device? Thank you very much.
```
$ nvidia-smi
Thu Aug 24 19:19:58 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100S-PCIE-32GB           On | 00000000:01:00.0 Off |                    0 |
| N/A   82C    P0              192W / 250W|  14892MiB / 32768MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100S-PCIE-32GB           On | 00000000:3E:00.0 Off |                    0 |
| N/A   40C    P0               37W / 250W|    576MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  Tesla V100S-PCIE-32GB           On | 00000000:B1:00.0 Off |                    0 |
| N/A   41C    P0               38W / 250W|    576MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  Tesla V100S-PCIE-32GB           On | 00000000:DA:00.0 Off |                    0 |
| N/A   44C    P0               35W / 250W|    576MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by subercui** [comment] 2023-08-25 01:11
Hi, you can find the GPUs that are currently supported by flash-attn in their repo readme. It looks like yours is not. Currently, the falsh-attn is still required for running. As indicated here https://github.com/bowang-lab/scGPT/issues/69#issuecomment-1692486050, we are currently working in the progress to expand the support. Will update the progress in #39 as well. Please stay tuned

**Comment by rpeys** [comment] 2023-09-20 20:31
Just wanted to add a similar experience I am having. My CUDA Version is 12.1. This doesn't allow me to install earlier versions of flash-attn<1.0.5 (there's a CUDA version mismatch issue which I documented here: https://github.com/Dao-AILab/flash-attention/issues/219#issuecomment-1719815517). This issue has since been fixed in the more recent releases of flash-attn, and I was able to succesfully install flash-attn 2.2.2. The problem is that the newer version of flash-attn seems to have breaking changes for scGPT. Specifically, when running the cell type annotation tutorial, I run up against this error when executing the line `model = TransformerModel(...`:

```
File ~/GitHub/scGPT/tutorials/../scgpt/model/model.py:109, in TransformerModel.__init__(self, ntoken, d_model, nhead, d_hid, nlayers, nlayers_cls, n_cls, vocab, dropout, pad_token, pad_value, do_mvc, do_dab, use_batch_labels, num_batch_labels, domain_spec_batchnorm, input_emb_style, n_input_bins, cell_emb_style, mvc_decoder_style, ecs_threshold, explicit_zero_prob, use_fast_transformer, fast_transformer_backend, pre_norm)
    105         self.transformer_encoder = FastTransformerEncoderWrapper(
    106             d_model, nhead, d_hid, nlayers, dropout
    107         )
    108     elif fast_transformer_backend == "flash":
--> 109         encoder_layers = FlashTransformerEncoderLayer(
    110             d_model,
    111             nhead,
    112             d_hid,
    113             dropout,
    114             batch_first=True,
    115             norm_scheme=self.norm_scheme,
    116         )
    117         self.transformer_encoder = TransformerEncoder(encoder_layers, nlayers)
    118 else:

File ~/GitHub/scGPT/tutorials/../scgpt/model/model.py:625, in FlashTransformerEncoderLayer.__init__(self, d_model, nhead, dim_feedforward, dropout, activation, layer_norm_eps, batch_first, device, dtype, norm_scheme)
    623 factory_kwargs = {"device": device, "dtype": dtype}
    624 super().__init__()
--> 625 self.self_attn = FlashMHA(
    626     embed_dim=d_model,
    627     num_heads=nhead,
    628     batch_first=batch_first,
    629     attention_dropout=dropout,
    630     **factory_kwargs,
    631 )
    632 # Implementation of Feedforward model
    633 self.linear1 = nn.Linear(d_model, dim_feedforward, **factory_kwargs)

NameError: name 'FlashMHA' is not defined
```

Looking through the flash-attn source code, they indeed did remove `flash_attn.flash_attention.FlashMHA` from version 2.2.2. Seems like flash-attn is quickly changing, so removing scGPT's dependency on it might be a good idea. Otherwise, would be great if scGPT could be updated to work with the latest version of flash_attn so that those of us with newer Nvidia drivers can use the code. Thanks for your hard work open-sourcing the code, esp with all the flash-attn troubles!

**Comment by moritzschaefer** [comment] 2023-12-11 06:44
@rpeys, did you use torch 2.1?

**Comment by moritzschaefer** [comment] 2023-12-11 06:48
@subercui thank you for the initial support in this issue. Indeed your suggested [code fix above]( https://github.com/bowang-lab/scGPT/issues/69#issuecomment-1691907507) seems to work. May I suggest to add it to the code base so future users ?

Versions: 
- flash-attn==1.0.4
- scgpt==1.0.9
- torch==2.1.1

**Comment by subercui** [comment] 2023-12-11 12:34
Hi @moritzschaefer , I think this case is only for using torch>=2.1.

**Comment by moritzschaefer** [comment] 2023-12-11 12:52
I see. So previous pytorch versions seem to implicitly add the `batch_first` attribute. 
I could offer to document my PR #133 more precisely indicating its intent to fix torch>=2.1 interoperability. Let me know.

**Comment by rpeys** [comment] 2023-12-11 14:27
> @rpeys, did you use torch 2.1? I am surprised you did not need to apply [the workaround above](https://github.com/bowang-lab/scGPT/issues/69#issuecomment-1691907507)

My torch version is 2.0.1. That would explain it.

**Comment by subercui** [comment] 2023-12-13 14:51
Hi, native pytorch 2.1 is now supported in the release v0.2.1. Please have a try and let me know if it works

**Closed by subercui** 2023-12-13 14:51 UTC
Labels: gpu-hardware

**Comment by AnonymousGym** [comment] 2024-01-16 06:41
Hopefully you can change the multiomic file also!

**Comment by Skyer19** [comment] 2024-07-04 16:56
> I now tested `v0.2.1` on `pytorch 2.1.2` (`cuda 12.1`, `flash-attn 1.0.4`), and it works fine. Note that the compatibility workaround is missing from `multiomic_model.py`. When added, it works as well.

Hi, I tested v0.2.1 on pytorch 2.1.2, flash-attn=1.0.4 with A100 GPU on python 3.9.19. But it still gave me "AttributeError: 'FlashMHA' object has no attribute 'batch_first'". May I know are there any parts that need to be modified?
