### ISSUE TITLE
IndexError: index 1 is out of bounds for dimension 1 with size 1

### ISSUE THREAD

**Issue by taffy-miao** [bowang-lab/scGPT#48] opened 2023-07-27 09:05 UTC
Hi Team
Your work is wonderful! I'm trying to run your perturbation tutorial, But I encountered a IndexError mistake.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_832306/3789924718.py in <module>
     10     train(
     11         model,
---> 12         train_loader,
     13     )
     14     val_loss, val_mre = evaluate(

/tmp/ipykernel_832306/701948179.py in train(model, train_loader)
     20         x: torch.Tensor = batch_data.x  # (batch_size * n_genes, 2)
     21         ori_gene_values = x[:, 0].view(batch_size, n_genes)
---> 22         pert_flags = x[:, 1].long().view(batch_size, n_genes)
     23         target_gene_values = batch_data.y  # (batch_size, n_genes)
     24 

IndexError: index 1 is out of bounds for dimension 1 with size 1

I'm using the adamson adata, and I check the shape of _x_, the result is torch.Size([323840, 1]), I wonder which step I did wrong.

**Comment by subercui** [comment] 2023-07-27 13:33
Hi, please use gears with a version before 0.0.4 for now. By default, pip should install `0.0.1`.  Please see the similar issue #36

**Comment by subercui** [comment] 2023-07-27 13:33
Duplicate of #36

**Comment by shenyeyouyi** [comment] 2023-07-28 03:36
Thanks! My current GEARS version is 0.0.4, I re-installed the version 0.0.1 and problem solved.
But I encounted another problem: While I download the _ADAMSON_ dataset for the first time using the code `pert_data.load(data_name=data_name)`

`pert_data.prepare_split(split=split, seed=1)`

`pert_data.get_dataloader(batch_size=batch_size, test_batch_size=eval_batch_size)`
everything is normal. But when I using the same code for the second time, it came several mistakes. I checked pert_data.adata.obs and found that the 'split' column gone, so I had to delete the './data' file and download the same dataset again.I wonder how to solve this problem.

**Comment by subercui** [comment] 2023-07-28 20:53
Hi, did you delete the data and redownload it after switching versions? I know that the 0.0.1 version of gears would create the "split" column only at the first time processing the data, while loading the data should still be fine at later times.

Basically, if you already have everything redownloaded and recreated with 0.0.1 now, can you try it again and let me know if it works?

**Comment by shenyeyouyi** [comment] 2023-07-29 10:56
Yes, I solved the problem by completely delete the data in ./data file and re-download it through running the `pert_data.load(data_name=data_name)` code. 
After the gears add the 'split' column, I saved this adata locally. Then I re-named the file as perturb_processed.h5ad., restarted jupyter and ran the code:
`pert_data = PertData("./")`
`pert_data.load(data_path = './my_perturb/')`
`pert_data.prepare_split(split=split, seed=1)`
`pert_data.get_dataloader(batch_size=batch_size, test_batch_size=eval_batch_size)`
And it also worked perfectly. But I didn't test whether gears would add the split column if there's no split column from the local file by using the codes above.
I'll let you know after I test it.

**Closed** 2023-08-07 15:27 UTC
