### ISSUE TITLE
Can we have requirements.txt to get required environment?

### ISSUE THREAD

**Issue by HelloWorldLTY** [bowang-lab/scGPT#10] opened 2023-05-19 01:35 UTC
It seems that installing torchtext requires torch 2.0.1, even if pip install scgpt does not require. What is the solution for it? Thanks a lot.

**Comment by subercui** [comment] 2023-05-19 04:40
Hi, we fixed the torchtext version requirement in the release, it is supposed to work out of the box. To see what is going on, can you let me know the method you used to install? poetry or pip install?

**Comment by HelloWorldLTY** [comment] 2023-05-19 12:12
pip install. Do I need to reinstall? Thanks.

**Comment by subercui** [comment] 2023-05-22 16:45
If you `pip install scgpt` and the version is 0.1.2. It is supposed to specifically install `pytorch==1.13.0` and `torchtext==0.14.0`. Those should work out fine, and they are listed in the [pyproject.toml](https://github.com/bowang-lab/scGPT/blob/v0.1.2/pyproject.toml)

In general, if scgpt is already installed via pip, you don't need to reinstall. You can check what pytorch and torchtext version you have by the command `pip list | grep torch`

If you want to play with other pytorch versions, I'll suggest you run the pytorch and torchtext install in one line, `pip install torch==x.x.x torchtext`. This command should automatically pick up the correct versions. Additionally, you may look at the https://github.com/pytorch/text repo and manually find the torchtext version you need. I would think this is the ultimate way to resolve the compatibility.

**Comment by killerz99** [comment] 2023-05-23 20:52
Hi,

I've tried to install with pip but keep running into various issues.  I tried to go back to the poety install but i hit this issue with 'packaging' not found even though I explicity install it before running poetry.  Any clue? 

Some other potential problems, I'm running CUDA V12.1 but poety/pip is installing cu11 by uninstalling v12 and can't uninstall the previous llvmlite package.  If I try to install on a V11.4 system it says cannot find a version of scgpt that satifies the requirement.

#0 100.4   • Installing wandb (0.12.21)
#0 100.4   • Installing transformers (4.20.1)
#0 100.4   • Installing torchtext (0.14.0)
#0 105.3 
#0 105.3   ChefBuildError
#0 105.3 
#0 105.3   Backend subprocess exited when trying to invoke get_requires_for_build_wheel
#0 105.3   
#0 105.3   Traceback (most recent call last):
#0 105.3     File "/root/.local/share/pypoetry/venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
...
#0 105.3     File "<string>", line 6, in <module>
**#0 105.3   ModuleNotFoundError: No module named 'packaging'**
#0 105.3   
#0 105.3 
#0 105.3   at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/installation/chef.py:147 in _prepare
#0 105.3       143│ 
#0 105.3       144│                 error = ChefBuildError("\n\n".join(message_parts))
...
#0 105.3 Note: This error originates from the build backend, and is likely not a problem with poetry but with flash-attn (1.0.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "flash-attn (==1.0.1)"'.
#0 105.3

**Comment by HelloWorldLTY** [comment] 2023-05-23 22:33
Could you please release something like requirement.txt? I also faced installation failing for scgpt from pip install. My problem is in flash attn, the cuda version is always incorrect.

**Comment by subercui** [comment] 2023-05-24 02:56
> Hi,
> 
> I've tried to install with pip but keep running into various issues. I tried to go back to the poety install but i hit this issue with 'packaging' not found even though I explicity install it before running poetry. Any clue?
> 
> Some other potential problems, I'm running CUDA V12.1 but poety/pip is installing cu11 by uninstalling v12 and can't uninstall the previous llvmlite package. If I try to install on a V11.4 system it says cannot find a version of scgpt that satifies the requirement.

Hi, I'll recommend cuda version 11.7 and above. I think 11.7 is also the minimal requirement in "flash-attn>=1.0.1". 

@killerz99  Regarding the poetry install issue with flash-attn, can you try `poetry run pip install flash-attn` in your current workspace. This is a walkaround to manually install a dependency in poetry env. If it works, poetry would skip this dependency. Then you can rerun `poetry install` afterwards, and it should work.

**Comment by subercui** [comment] 2023-05-24 03:02
So it seems a lot of the errors discussed are related to flash-attn. To be honest, although the `flash-attn` is super awesome to me, the package is rather new and there is indeed a lot of [discussion](https://github.com/HazyResearch/flash-attention/issues) related to its installation. It is known to be quite picky about cuda versions.

**Comment by subercui** [comment] 2023-05-24 03:06
> Hi all, I think i find an approch to install and check the scGPT successfully.
> 
> The first step is to use pip install scgpt The second step is to use conda to install cuda with version 11.7. The third step is uninstall the flash-attn (default 1.0.5 version) and install 1.0.4 version with pip install flash-attn==1.0.4.
> 
> Now this approach works for me, without extra errors.

@HelloWorldLTY  Thank you for offering this approach. Is there a reason for your last step of resintalling `flash-attn==1.0.4`? So the `1.0.5` does not work for you, does it?

**Comment by HelloWorldLTY** [comment] 2023-05-24 03:08
> > Hi all, I think i find an approch to install and check the scGPT successfully.
> > The first step is to use pip install scgpt The second step is to use conda to install cuda with version 11.7. The third step is uninstall the flash-attn (default 1.0.5 version) and install 1.0.4 version with pip install flash-attn==1.0.4.
> > Now this approach works for me, without extra errors.
> 
> @HelloWorldLTY Thank you for offering this approach. Is there a reason for your last step of resintalling `flash-attn==1.0.4`? So the `1.0.5` does not work for you, does it?

Yes, 1.0.5 does not work for me because of the version of CUDA. I think if you have cuda version like 12.1, for example, 1.0.5 is a better choice. However, I have cuda version like 11.3 or 11.7, so it does not fit my case.

**Comment by HelloWorldLTY** [comment] 2023-05-24 04:27
Here is my output for some epoches:


random masking at epoch  16, ratio of masked values in train:  0.3997
scGPT - INFO - | epoch  16 | 100/170 batches | lr 0.0000 | ms/batch 540.39 | loss 104.95 | mse 46.54 | mre 1491543.67 |gepc 47.57 |
scGPT - INFO - -----------------------------------------------------------------------------------------
scGPT - INFO - | end of epoch  16 | time: 94.15s | valid loss/mse 44.8812 | mre 1343236.8438
scGPT - INFO - -----------------------------------------------------------------------------------------
random masking at epoch  17, ratio of masked values in train:  0.3997
scGPT - INFO - | epoch  17 | 100/170 batches | lr 0.0000 | ms/batch 552.01 | loss 105.65 | mse 46.42 | mre 1472369.21 |gepc 48.22 |
scGPT - INFO - -----------------------------------------------------------------------------------------
scGPT - INFO - | end of epoch  17 | time: 95.64s | valid loss/mse 44.7859 | mre 1477005.8320
scGPT - INFO - -----------------------------------------------------------------------------------------
random masking at epoch  18, ratio of masked values in train:  0.3997
scGPT - INFO - | epoch  18 | 100/170 batches | lr 0.0000 | ms/batch 554.27 | loss 104.83 | mse 46.48 | mre 1486923.72 |gepc 47.45 |
scGPT - INFO - -----------------------------------------------------------------------------------------
scGPT - INFO - | end of epoch  18 | time: 96.12s | valid loss/mse 44.8377 | mre 1463559.5581
scGPT - INFO - -----------------------------------------------------------------------------------------
random masking at epoch  19, ratio of masked values in train:  0.3997

However, I have some questions about it. Why the mse and mre are so large? Moreover, did you observe the emergent ability of scGPT? I believe this should be a common feature for all the LLM.

If you need I can output my conda environment information and send it to you, as another option for install. Thanks a lot

**Comment by killerz99** [comment] 2023-05-27 00:56
so if I run
poetry run pip install flash-attn

it tries to install cuda 11.7 even though I already have cuda 12.1 installed.

#0 136.1 Collecting jinja2 (from torch->flash-attn)
#0 136.1   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
#0 136.1      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 249.4 MB/s eta 0:00:00
#0 136.3 Collecting nvidia-cuda-nvrtc-cu11==11.7.99 (from torch->flash-attn)
#0 136.3   Downloading nvidia_cuda_nvrtc_cu11-11.7.99-2-py3-none-manylinux1_x86_64.whl (21.0 MB)

which ultimately ends up in a cuda mismatch

#0 169.4       The detected CUDA version (12.1) mismatches the version that was used to compile
#0 169.4       PyTorch (11.7). Please make sure to use the same CUDA versions.

**Comment by cx0** [comment] 2023-05-30 12:36
Hi @subercui - could you please share the `pip freeze` output of a working version (preferably along with CUDA version information)? It is challenging to track down the culprit for the dependency issue. Downgrading (or reinstalling) flash-attn did not work for me when I try to pip install on colab. Thank you.

**Comment by amcdavid** [comment] 2023-05-31 23:14
I would echo these comments -- I have run into all sorts of issues with missing symbols in flash-attn, despite matching the pytorch and CUDA versions indicated in the pyproject.toml, and installing on fresh EC2 instances.  `pip freeze` and `lsb_release -d` would be very helpful in allowing others to understand what system requirements are needed to reproduce this.

**Comment by subercui** [comment] 2023-05-31 23:44
@cx0 @amcdavid Thanks for the suggestions. I'll give it and share the output with you.

On the other hand, I doubt whether `pip freeze` can help with this issue. I would guess this is not because scGPT doesn't support certain flash-attn versions, rather, it would more likely be flash-attn didn't install properly itself. So I also have several suggestions to help you debug it:

1. If you can choose your CUDA version, I would suggest using CUDA 11.7 and flash-attn<1.0.5. Please see this new note here as well https://github.com/bowang-lab/scGPT#installation

2. If the `pip install` encounters errors with flash-attn, please have a look at their issues. There seems to be quite some issues recently, particularly with their versions>=1.0.5. To name a few:
    https://github.com/HazyResearch/flash-attention/issues/246
    https://github.com/HazyResearch/flash-attention/issues/231
    https://github.com/HazyResearch/flash-attention/issues/203

3. If you have installed flash-attn, try running one of their benchmarking or test scripts. For example, https://github.com/HazyResearch/flash-attention/blob/main/benchmarks/benchmark_flash_attention.py . This will tell whether the package is working properly

**Comment by subercui** [comment] 2023-05-31 23:56
Please find the outputs of `pip freeze`, `lsb_release -d`, `nvcc --version` [here](https://gist.github.com/subercui/a43d86906a0ab7fc555340bdecf5e464)

**Comment by subercui** [comment] 2023-06-07 18:07
If there are no further inquiries regarding the installation environment, I would like to proceed with closing this issue.

@HelloWorldLTY I am more than glad to continue our discussion about fine-tuning in a separate issue if you feel like to as well

**Comment by HelloWorldLTY** [comment] 2023-06-07 18:12
Hi, thanks a lot. I will share my yaml file to you via email.

For fine tuning task, I am still looking though the process. I will let you know if I have futher qustion. Many thanks for your great work!

**Closed** 2023-06-10 15:23 UTC
Labels: installation
