### ISSUE TITLE
TypeError: ~ (operator.invert) is only implemented on integer and Boolean-type tensors

### ISSUE THREAD

**Issue by AbdulSabb** [bowang-lab/scGPT#53] opened 2023-08-01 14:45 UTC
Hi, I tried to run the `tutorials/Tutorial_Annotation.ipynb` notebook, and I had the following error when running the training cell as shown below:
```
TypeError                                 Traceback (most recent call last)
Cell In[46], line 25
     16 valid_loader = prepare_dataloader(
     17     valid_data_pt,
     18     batch_size=eval_batch_size,
   (...)
     21     drop_last=False,
     22 )
     24 if config.do_train:
---> 25     train(
     26         model,
     27         loader=train_loader,
     28     )
     29 val_loss, val_err = evaluate(
     30     model,
     31     loader=valid_loader,
     32 )
     33 elapsed = time.time() - epoch_start_time

Cell In[45], line 35, in train(model, loader)
     33 ###
     34 with torch.cuda.amp.autocast(enabled=config.amp):
---> 35     output_dict = model(
     36         input_gene_ids,
     37         input_values,
     38         src_key_padding_mask=src_key_padding_mask,
     39         batch_labels=batch_labels if INPUT_BATCH_LABELS or config.DSBN else None,
     40         CLS=CLS,
     41         CCE=CCE,
     42         MVC=MVC,
     43         ECS=ECS,
     44         do_sample=do_sample_in_train,
     45         #generative_training=False
     46     )
     48     masked_positions = input_values.eq(mask_value)  # the postions to predict
     49     loss = 0.0

File /ibex/user/sabbam0a/template/env/lib/python3.8/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File /ibex/user/sabbam0a/template/env/lib/python3.8/site-packages/scgpt/model/model.py:327, in TransformerModel.forward(self, src, values, src_key_padding_mask, batch_labels, CLS, CCE, MVC, ECS, do_sample)
    296 def forward(
    297     self,
    298     src: Tensor,
   (...)
    306     do_sample: bool = False,
    307 ) -> Mapping[str, Tensor]:
    308     """
    309     Args:
    310         src (:obj:`Tensor`): token ids, shape [batch_size, seq_len]
   (...)
    325         dict of output Tensors.
    326     """
--> 327     transformer_output = self._encode(
    328         src, values, src_key_padding_mask, batch_labels
    329     )
    330     if self.use_batch_labels:
    331         batch_emb = self.batch_encoder(batch_labels)  # (batch, embsize)

File /ibex/user/sabbam0a/template/env/lib/python3.8/site-packages/scgpt/model/model.py:176, in TransformerModel._encode(self, src, values, src_key_padding_mask, batch_labels)
    173 else:
    174     total_embs = self.bn(total_embs.permute(0, 2, 1)).permute(0, 2, 1)
--> 176 output = self.transformer_encoder(
    177     total_embs, src_key_padding_mask=src_key_padding_mask
    178 )
    179 return output

File /ibex/user/sabbam0a/template/env/lib/python3.8/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File /ibex/user/sabbam0a/template/env/lib/python3.8/site-packages/torch/nn/modules/transformer.py:315, in TransformerEncoder.forward(self, src, mask, src_key_padding_mask, is_causal)
    312 is_causal = make_causal
    314 for mod in self.layers:
--> 315     output = mod(output, src_mask=mask, is_causal=is_causal, src_key_padding_mask=src_key_padding_mask_for_layers)
    317 if convert_to_nested:
    318     output = output.to_padded_tensor(0.)

File /ibex/user/sabbam0a/template/env/lib/python3.8/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File /ibex/user/sabbam0a/template/env/lib/python3.8/site-packages/scgpt/model/model.py:682, in FlashTransformerEncoderLayer.forward(self, src, src_mask, src_key_padding_mask, **kwargs)
    679     src_key_padding_mask_ = None
    680 else:
    681     # NOTE: the FlashMHA uses mask 0 for padding tokens, which is the opposite
--> 682     src_key_padding_mask_ = ~src_key_padding_mask
    684 if self.norm_scheme == "pre":
    685     src = self.norm1(src)

TypeError: ~ (operator.invert) is only implemented on integer and Boolean-type tensors
```

While when `src_key_padding_mask` is printed the value is:
```
tensor([[False, False, False,  ...,  True,  True,  True],
        [False, False, False,  ...,  True,  True,  True],
        [False, False, False,  ...,  True,  True,  True],
        ...,
        [False, False, False,  ...,  True,  True,  True],
        [False, False, False,  ...,  True,  True,  True],
        [False, False, False,  ...,  True,  True,  True]], device='cuda:0')
```
        
pytorch_2.0.0-cuda11.7

Could you please suggest a solution?
Thanks

**Comment by subercui** [comment] 2023-08-01 22:53
Hi, this looks like a duplicate of #35 .  Please have a look at https://github.com/bowang-lab/scGPT/issues/35#issuecomment-1632650059

Please try to use the code in the main branch for now. The update hasn't been pushed to pypi. To use the main branch code:
```shell
# suppose you already have a working env with all dependencies
git clone https://github.com/bowang-lab/scGPT.git
cd scGPT/tutorials
```
Then when you run the notebook or another python script, make sure you import the downloaded scGPT by
```python
import sys
sys.path.insert(0, "../")
import scgpt as scg
```

Note these lines are also in the first cell in the tutorial notebook.

**Comment by subercui** [comment] 2023-08-01 22:59
Duplicate of #35

**Closed** 2023-08-07 14:55 UTC
