### ISSUE TITLE
Question about the dataloader of perturbation tutorial 

### ISSUE THREAD

**Issue by YimengQiao** [bowang-lab/scGPT#101] opened 2023-10-24 10:37 UTC
Hi, thanks for your great work! I am trying to run the perturbation tutorial, when executing the line
`pert_flags = x[:, 1].long().view(batch_size, n_genes)`
there would be an error
`IndexError: index 1 is out of bounds for dimension 1 with size 1.`

I noticed that you commented that the shape of batch_data.x should be (batch_size\*n_genes, 2), while I only got the batch_data.x shaped (batch_size\*n_genes, 1). I would like to ask were there some preprocessed tasks that I ignored (I just ran the tutorial without any other operations). Thanks for your response.

**Comment by subercui** [comment] 2023-10-28 02:02
Hi, thank you for the question! This seems like a similar one as #36, could you please try that solution and let me know if you have further questions?

Duplicate of #36

**Comment by docmab23** [comment] 2023-11-11 08:08
I used the earlier version as specified in https://github.com/bowang-lab/scGPT/issues/36 , even after that I am getting this error, I am using version GEARS `v0.0.1`:

<img width="855" alt="image" src="https://github.com/bowang-lab/scGPT/assets/31487695/29c38f5e-f293-4e91-b47a-7c2c5c7543ce">

<img width="910" alt="image" src="https://github.com/bowang-lab/scGPT/assets/31487695/ae236095-e6a4-466d-8bd0-342fc26f4972">


This is how I am loading the `pert_data` 

<img width="696" alt="image" src="https://github.com/bowang-lab/scGPT/assets/31487695/c38f8364-c37a-4b5b-8045-fa7921aadf53">


Your valuable input would be appreciated!
Thanks

**Comment by subercui** [comment] 2023-11-11 22:20
Hi, you will need to delete the data files after the reinstallation and then it should work.

**Comment by docmab23** [comment] 2023-11-11 23:20
Thanks. Also, is there a way you can provide the fine-tuned model for pertubation prediction as well. Maybe a google drive link, if possible. Thanks

**Comment by YimengQiao** [comment] 2023-11-15 03:14
> Hi, thank you for the question! This seems like a similar one as #36, could you please try that solution and let me know if you have further questions?
> 
> Duplicate of #36

Sorry for the late response. It worked when using gears v0.0.1. The only problem is that the pert_flag vectors seem like taking up too much memory. Thank you very much!

**Closed** 2023-12-11 13:38 UTC

**Comment by Yonggie** [comment] 2024-03-27 08:40
Just checked the source code of gears==0.0.1, should do some extra change at the same time:
change ``pert_data.dataloader[xxx]`` into ``pert_data.get_dataloader(**required_para)[xxx]``.

It worked.
